export default {
    heroimage:require("./HeroNew.webp"),
    logo:require("./logo.png"),
    ResidentialImage:require("./ResidentialImage.png"),
    CommercialImage:require("./CommercialImage.png") ,
    IndustrialImage:require("./IndustrialImage.png") ,
    ConsultancyImage:require("./ConsultancyImage.png"),
    ac:require("./ac.jpeg"),
    heating:require("./Heating.jpg"),
    hvacsystem:require("./HVAC Maintanance.jpg"),
    energy:require("./EnergyEfficiency.jpg"),
    ventilation:require("./Ventilation.jpg"),
    blog1:require("./blog1.jpg"),
    blog2:require("./blog2.jpg"),
    blog3:require("./blog3.jpg"),
    blog4:require("./blog4.jpg"),
    union:require("./Union.png"),
    team:require("./team.png"),
    future:require("./future.png"),
    end:require("./endend.png"),
    customer:require("./customer.png"),
    doodlebg:require("./doodle-bg.png"),
    spark:require("./spark.png"),
    hvac:require("./fluent_weather-duststorm.png"),
    swimming:require("./fluent_swimming-pool.png"),
    electrical:require("./streamline_electric-cord.png"),
    trading:require("./lsicon_goods-outline.png"),
    swimmingpool:require("./swimming-pool.jpg"),
    electric:require("./Electric.jpg"),
    trade:require("./Equipment.png"),
    



}